import hashlib
import os
import time
import traceback

from . import SCHEMA_VERSION, TOOL_VERSION
from .common import enum_name, resource_id, sha256_file, structural_hash, utc_now
from .pass_graph import build_pass_graph, usage_sets


def _progress(stage):
    path = os.environ.get("RDX_ANALYSIS_PROGRESS")
    if not path:
        return
    try:
        with open(path, "a", encoding="utf-8", newline="\n") as stream:
            stream.write("{} {}\n".format(utc_now(), stage))
            stream.flush()
    except OSError:
        pass


def _contains(flags, value):
    try:
        return bool(flags & value)
    except (TypeError, ValueError):
        try:
            return (int(flags) & int(value)) != 0
        except (TypeError, ValueError):
            return False


def _result(result):
    if result is None:
        return {"code": "Unknown", "message": "No result returned"}
    code = enum_name(getattr(result, "code", result))
    try:
        message = str(result.Message())
    except Exception:
        message = str(result)
    return {"code": code, "message": message}


def _format_name(value):
    try:
        return str(value.Name())
    except Exception:
        return enum_name(getattr(value, "type", value))


def _memory_usage(rd):
    try:
        return int(rd.GetCurrentProcessMemoryUsage())
    except Exception:
        return None


def _flatten_actions(rd, controller):
    structured = controller.GetStructuredFile()
    actions = []

    def visit(items, parent_event_id=None, depth=0):
        for action in items:
            flags = action.flags
            flag_names = []
            for name in (
                "Clear",
                "Drawcall",
                "Dispatch",
                "MeshDispatch",
                "Present",
                "MultiAction",
                "Copy",
                "Resolve",
                "GenMips",
                "PassBoundary",
                "DispatchRay",
                "BuildAccStruct",
                "Indexed",
                "Instanced",
                "Indirect",
                "BeginPass",
                "EndPass",
            ):
                flag = getattr(rd.ActionFlags, name, None)
                if flag is not None and _contains(flags, flag):
                    flag_names.append(name)
            try:
                name = str(action.GetName(structured))
            except Exception:
                name = str(getattr(action, "customName", ""))
            record = {
                "eventId": int(action.eventId),
                "actionId": int(action.actionId),
                "parentEventId": parent_event_id,
                "depth": depth,
                "name": name,
                "flags": flag_names,
                "numIndices": int(getattr(action, "numIndices", 0)),
                "numInstances": int(getattr(action, "numInstances", 0)),
                "drawIndex": int(getattr(action, "drawIndex", 0)),
                "children": [int(child.eventId) for child in action.children],
            }
            actions.append(record)
            visit(action.children, int(action.eventId), depth + 1)

    visit(controller.GetRootActions())
    return sorted(actions, key=lambda item: (item["eventId"], item["actionId"]))


def _resource_summaries(rd, controller):
    descriptions = list(controller.GetResources())
    textures = list(controller.GetTextures())
    buffers = list(controller.GetBuffers())
    texture_by_id = {resource_id(item.resourceId): item for item in textures}
    buffer_by_id = {resource_id(item.resourceId): item for item in buffers}
    records = []
    resource_keys = {}

    for description in descriptions:
        identifier = resource_id(description.resourceId)
        resource_type = enum_name(description.type)
        record = {
            "resourceId": identifier,
            "type": resource_type,
            "name": str(description.name),
            "autogeneratedName": bool(description.autogeneratedName),
            "parents": [
                value
                for value in (resource_id(item) for item in description.parentResources)
                if value
            ],
            "derived": [
                value
                for value in (resource_id(item) for item in description.derivedResources)
                if value
            ],
        }

        texture = texture_by_id.get(identifier)
        if texture is not None:
            details = {
                "format": _format_name(texture.format),
                "dimension": int(texture.dimension),
                "width": int(texture.width),
                "height": int(texture.height),
                "depth": int(texture.depth),
                "mips": int(texture.mips),
                "arraySize": int(texture.arraysize),
                "samples": int(texture.msSamp),
                "byteSize": int(texture.byteSize),
                "creationFlags": str(texture.creationFlags),
            }
            record["texture"] = details
            resource_keys[identifier] = structural_hash({"kind": "texture", "details": details})

        buffer = buffer_by_id.get(identifier)
        if buffer is not None:
            details = {
                "length": int(buffer.length),
                "creationFlags": str(buffer.creationFlags),
            }
            record["buffer"] = details
            resource_keys[identifier] = structural_hash({"kind": "buffer", "details": details})

        if identifier and identifier not in resource_keys:
            resource_keys[identifier] = structural_hash({"kind": resource_type})
        records.append(record)

    records.sort(key=lambda item: item["resourceId"] or "")
    return {
        "counts": {
            "resources": len(descriptions),
            "textures": len(textures),
            "buffers": len(buffers),
            "shaders": sum(
                enum_name(description.type) == "Shader" for description in descriptions
            ),
        },
        "resources": records,
        "resourceKeys": resource_keys,
    }


def _main_output(rd, controller, resource_summary):
    candidates = []
    for resource in resource_summary["resources"]:
        texture = resource.get("texture")
        if texture is None:
            continue
        if "SwapBuffer" in texture["creationFlags"]:
            candidates.append(resource)
    if not candidates:
        return {
            "status": "unknown",
            "reason": "No texture marked as a swapchain buffer",
        }
    selected = max(
        candidates,
        key=lambda item: item["texture"]["width"] * item["texture"]["height"],
    )
    texture = selected["texture"]
    return {
        "status": "confirmed",
        "resourceId": selected["resourceId"],
        "width": texture["width"],
        "height": texture["height"],
        "format": texture["format"],
        "samples": texture["samples"],
    }


def _debug_messages(rd, controller):
    frame_messages = list(controller.GetFrameInfo().debugMessages)
    replay_messages = list(controller.GetDebugMessages())
    messages = []
    seen = set()
    for message in frame_messages + replay_messages:
        record = {
            "eventId": int(getattr(message, "eventId", 0)),
            "messageId": int(getattr(message, "messageID", 0)),
            "source": enum_name(getattr(message, "source", None)),
            "severity": enum_name(getattr(message, "severity", None)),
            "category": enum_name(getattr(message, "category", None)),
            "description": str(getattr(message, "description", "")),
        }
        key = (
            record["eventId"],
            record["messageId"],
            record["source"],
            record["description"],
        )
        if key not in seen:
            seen.add(key)
            messages.append(record)
    return messages


def _resource_usages(controller, resource_summary):
    usages = []
    resource_objects = {
        resource_id(item.resourceId): item.resourceId for item in controller.GetResources()
    }
    for resource in resource_summary["resources"]:
        if "texture" not in resource and "buffer" not in resource:
            continue
        identifier = resource["resourceId"]
        try:
            resource_object = resource_objects[identifier]
            entries = [
                {"eventId": int(item.eventId), "usage": enum_name(item.usage)}
                for item in controller.GetUsage(resource_object)
            ]
        except Exception as exception:
            entries = []
            resource["usageError"] = str(exception)
        usages.append({"resourceId": identifier, "usages": entries})
    return usages


def _viewport(pipe):
    try:
        viewport = pipe.GetViewport(0)
        return {
            "enabled": bool(viewport.enabled),
            "x": float(viewport.x),
            "y": float(viewport.y),
            "width": float(viewport.width),
            "height": float(viewport.height),
            "minDepth": float(viewport.minDepth),
            "maxDepth": float(viewport.maxDepth),
        }
    except Exception:
        return None


def _shader_stages(rd):
    stages = []
    for name in (
        "Vertex",
        "Hull",
        "Domain",
        "Geometry",
        "Pixel",
        "Compute",
        "Task",
        "Mesh",
        "RayGen",
        "Intersection",
        "AnyHit",
        "ClosestHit",
        "Miss",
        "Callable",
    ):
        value = getattr(rd.ShaderStage, name, None)
        if value is not None:
            stages.append((name, value))
    return stages


def _action_signatures(rd, controller, actions, resource_summary, resource_usages):
    work_actions = [
        action
        for action in actions
        if not action["children"]
        and any(
            flag in action["flags"]
            for flag in ("Drawcall", "Dispatch", "MeshDispatch", "DispatchRay")
        )
    ]
    per_action = usage_sets(actions, resource_usages)
    resource_keys = resource_summary["resourceKeys"]
    textures = {
        resource["resourceId"]: resource["texture"]
        for resource in resource_summary["resources"]
        if "texture" in resource
    }
    shader_cache = {}
    shader_records = {}
    signatures = []

    for relative_order, action in enumerate(work_actions):
        event_id = action["eventId"]
        controller.SetFrameEvent(event_id, False)
        pipe = controller.GetPipelineState()
        is_compute = any(
            flag in action["flags"] for flag in ("Dispatch", "MeshDispatch", "DispatchRay")
        )
        pipeline_object = (
            pipe.GetComputePipelineObject() if is_compute else pipe.GetGraphicsPipelineObject()
        )
        shader_bindings = []
        shader_hashes = []

        for stage_name, stage in _shader_stages(rd):
            shader = pipe.GetShader(stage)
            shader_identifier = resource_id(shader)
            if shader_identifier is None:
                continue
            entry_point = str(pipe.GetShaderEntryPoint(stage))
            cache_key = (resource_id(pipeline_object), shader_identifier, stage_name, entry_point)
            cached = shader_cache.get(cache_key)
            if cached is None:
                reflection = pipe.GetShaderReflection(stage)
                disassembly = ""
                fidelity = "exact"
                try:
                    if reflection is not None:
                        disassembly = str(
                            controller.DisassembleShader(pipeline_object, reflection, "")
                        )
                except Exception:
                    disassembly = ""
                if disassembly:
                    shader_hash = hashlib.sha256(disassembly.encode("utf-8")).hexdigest().upper()
                else:
                    fidelity = "approximation"
                    shader_hash = structural_hash(
                        {
                            "shaderResourceId": shader_identifier,
                            "stage": stage_name,
                            "entryPoint": entry_point,
                        }
                    )
                cached = {
                    "resourceId": shader_identifier,
                    "stage": stage_name,
                    "entryPoint": entry_point,
                    "disassemblySHA256": shader_hash,
                    "hashFidelity": fidelity,
                }
                shader_cache[cache_key] = cached
                shader_records[
                    (shader_identifier, stage_name, entry_point, shader_hash)
                ] = cached
            shader_bindings.append(cached)
            shader_hashes.append(cached["disassemblySHA256"])

        output_resources = []
        render_target_formats = []
        try:
            for target in pipe.GetOutputTargets():
                identifier = resource_id(target.resource)
                if identifier:
                    output_resources.append(identifier)
                    render_target_formats.append(
                        textures.get(identifier, {}).get(
                            "format", _format_name(target.format)
                        )
                    )
            depth = pipe.GetDepthTarget()
            depth_identifier = resource_id(depth.resource)
            if depth_identifier:
                output_resources.append(depth_identifier)
                render_target_formats.append(
                    textures.get(depth_identifier, {}).get(
                        "format", _format_name(depth.format)
                    )
                )
        except Exception:
            pass

        usage = per_action[event_id]
        input_resources = sorted(usage["reads"])
        output_resources = sorted(set(output_resources) | usage["writes"])
        viewport = _viewport(pipe)
        state = {
            "workClass": "compute" if is_compute else "graphics",
            "topology": enum_name(pipe.GetPrimitiveTopology()),
            "pipelineObject": resource_id(pipeline_object),
            "shaderHashes": sorted(shader_hashes),
            "inputResourceKeys": sorted(
                resource_keys.get(identifier, identifier) for identifier in input_resources
            ),
            "outputResourceKeys": sorted(
                resource_keys.get(identifier, identifier) for identifier in output_resources
            ),
            "viewport": viewport,
            "renderTargetFormats": render_target_formats,
        }
        pipeline_hash = structural_hash(state)
        kind = next(
            (
                flag
                for flag in ("Drawcall", "Dispatch", "MeshDispatch", "DispatchRay")
                if flag in action["flags"]
            ),
            "Unknown",
        )
        signature_basis = {
            "kind": kind,
            "relativeOrder": relative_order,
            "pipelineStateHash": pipeline_hash,
            "inputResourceKeys": state["inputResourceKeys"],
            "outputResourceKeys": state["outputResourceKeys"],
        }
        signatures.append(
            {
                "eventId": event_id,
                "actionId": action["actionId"],
                "kind": kind,
                "workClass": state["workClass"],
                "relativeOrder": relative_order,
                "pipelineObject": state["pipelineObject"],
                "pipelineStateHash": pipeline_hash,
                "shaderBindings": shader_bindings,
                "shaderHashes": sorted(shader_hashes),
                "inputResources": input_resources,
                "outputResources": output_resources,
                "inputResourceKeys": state["inputResourceKeys"],
                "outputResourceKeys": state["outputResourceKeys"],
                "viewport": viewport,
                "renderTargetFormats": render_target_formats,
                "structuralSignature": structural_hash(signature_basis),
            }
        )

    return signatures, sorted(
        shader_records.values(),
        key=lambda item: (
            item["resourceId"],
            item["stage"],
            item["entryPoint"],
        ),
    )


def analyse_capture(capture_path):
    import renderdoc as rd

    started = time.monotonic()
    _progress("analysis-start")
    result = {
        "schemaVersion": SCHEMA_VERSION,
        "kind": "capture-analysis-worker-result",
        "toolVersion": TOOL_VERSION,
        "generatedAt": utc_now(),
        "capturePath": os.path.abspath(capture_path),
        "captureSHA256": sha256_file(capture_path),
        "captureSizeBytes": os.path.getsize(capture_path),
        "status": "failed",
        "captureVersion": {
            "status": "unknown",
            "value": None,
            "reason": "The public CaptureFile API does not expose the RDC format version",
        },
        "replayVersion": str(rd.GetVersionString()),
    }
    peak_memory = _memory_usage(rd)
    cap = None
    controller = None

    try:
        _progress("capture-open-create")
        cap = rd.OpenCaptureFile()
        _progress("capture-open-file")
        open_result = cap.OpenFile(result["capturePath"], "", None)
        _progress("capture-open-file-complete")
        result["openResult"] = _result(open_result)
        result["driver"] = str(cap.DriverName())
        result["localReplaySupport"] = enum_name(cap.LocalReplaySupport())
        result["recordedMachineIdent"] = str(cap.RecordedMachineIdent())
        result["missingDependencies"] = {
            "pending": bool(cap.HasPendingDependencies()),
            "embedded": bool(cap.HasEmbeddedDependencies()),
            "nicknames": [str(item) for item in cap.GetPendingDependenciesNicknames()],
        }
        if open_result != rd.ResultCode.Succeeded:
            return result

        _progress("replay-open")
        replay_result, controller = cap.OpenCapture(rd.ReplayOptions(), None)
        _progress("replay-open-complete")
        result["replayResult"] = _result(replay_result)
        if replay_result != rd.ResultCode.Succeeded or controller is None:
            return result

        memory_values = [
            value for value in (peak_memory, _memory_usage(rd)) if value is not None
        ]
        peak_memory = max(memory_values) if memory_values else None
        properties = controller.GetAPIProperties()
        result["api"] = enum_name(properties.pipelineType)
        result["localRenderer"] = enum_name(properties.localRenderer)
        result["gpuVendor"] = enum_name(properties.vendor)
        result["remoteReplay"] = bool(properties.remoteReplay)
        result["degradedReplay"] = bool(properties.degraded)

        try:
            driver_info = rd.GetDriverInformation(properties.pipelineType)
            result["driverInformation"] = {
                "vendor": enum_name(driver_info.vendor),
                "version": str(driver_info.version),
            }
        except Exception as exception:
            result["driverInformation"] = {
                "status": "unknown",
                "reason": str(exception),
            }

        _progress("actions")
        actions = _flatten_actions(rd, controller)
        _progress("resources")
        resources = _resource_summaries(rd, controller)
        _progress("resource-usages")
        resource_usages = _resource_usages(controller, resources)
        _progress("action-signatures")
        action_signatures, bound_shaders = _action_signatures(
            rd, controller, actions, resources, resource_usages
        )
        _progress("pass-graph")
        graph = build_pass_graph(actions, resource_usages, action_signatures)
        _progress("debug-messages")
        messages = _debug_messages(rd, controller)
        fatal = controller.GetFatalErrorStatus()
        fatal_result = _result(fatal)

        counts = resources["counts"]
        result.update(
            {
                "actionCount": len(actions),
                "drawCount": sum("Drawcall" in action["flags"] for action in actions),
                "dispatchCount": sum(
                    any(
                        flag in action["flags"]
                        for flag in ("Dispatch", "MeshDispatch", "DispatchRay")
                    )
                    for action in actions
                ),
                "executeIndirectCount": sum(
                    action["name"].startswith("ExecuteIndirect") for action in actions
                ),
                "multiActionCount": sum(
                    "MultiAction" in action["flags"] for action in actions
                ),
                "indirectActionCount": sum(
                    "Indirect" in action["flags"] for action in actions
                ),
                "shaderCount": counts["shaders"],
                "textureCount": counts["textures"],
                "bufferCount": counts["buffers"],
                "mainOutput": _main_output(rd, controller, resources),
                "fatalError": fatal_result,
                "deviceLost": "DeviceLost" in fatal_result["code"]
                or "Device Lost" in fatal_result["message"],
                "unsupportedFeature": bool(properties.degraded)
                or any(
                    message["source"] == "UnsupportedConfiguration"
                    for message in messages
                ),
                "warningCount": sum(
                    message["severity"] in ("Medium", "Low") for message in messages
                ),
                "errorCount": sum(
                    message["severity"] == "High" for message in messages
                ),
                "missingDependencyCount": len(
                    result["missingDependencies"]["nicknames"]
                ),
                "messages": messages,
                "actions": actions,
                "resourceSummary": resources,
                "resourceUsages": resource_usages,
                "shaderSummary": {
                    "resourceShaderCount": counts["shaders"],
                    "boundShaders": bound_shaders,
                },
                "actionSignatures": action_signatures,
                "passGraph": graph,
            }
        )

        if fatal_result["code"] != "Succeeded":
            result["status"] = "failed"
        elif (
            result["degradedReplay"]
            or result["unsupportedFeature"]
            or result["errorCount"] > 0
            or result["missingDependencyCount"] > 0
        ):
            result["status"] = "degraded"
        else:
            result["status"] = "healthy"
        _progress("analysis-complete")
        return result
    except BaseException as exception:
        result["workerException"] = {
            "type": type(exception).__name__,
            "message": str(exception),
            "traceback": traceback.format_exc(),
        }
        return result
    finally:
        if controller is not None:
            try:
                _progress("controller-shutdown")
                controller.Shutdown()
            except Exception:
                pass
        if cap is not None:
            try:
                _progress("capture-shutdown")
                cap.Shutdown()
            except Exception:
                pass
        final_memory = _memory_usage(rd)
        values = [value for value in (peak_memory, final_memory) if value is not None]
        result["peakMemoryBytes"] = max(values) if values else None
        result["analysisDurationMs"] = int((time.monotonic() - started) * 1000)
        _progress("worker-finalized")
